export const slotBackgrounds: { [key: string]: string } = {
  HEAD: '0em',
  NECK: '-1em',
  SHOULDER: '-2em',
  SHIRT: '-3em',
  CHEST: '-4em',
  BELT: '-5em',
  LEGS: '-6em',
  FEET: '-7em',
  WRIST: '-8em',
  HAND: '-9em',
  FINGER: '-11em',
  SECOND_FINGER: '-11em',
  TRINKET: '-12em',
  SECOND_TRINKET: '-13em',
  BACK: '-14em',
  MAIN_HAND: '-15em',
  OFF_HAND: '-16em',
  TABARD: '-18em',
};
